name: MEDICINA BIOREGENERATIVA
favicon: null
layout_spectrum: 0.6458820586558431
typography_spectrum: 0.1072816385421902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3117729676887393
  lightness: 0.9588667864445597
  saturation: 0.3778168025892228
  rhythmicContrast: 0.9459466629195958
purpose: []
